ASSIGNMENT 1

102218069

Sidharth Dhawan



Q1. BASED ON BASIC NUMPY ARRAY

Importing Numpy

In [18]:
import numpy as np

A. Reverse the NumPy array:
arr = np.array([1, 2, 3, 6, 4, 5])

In [19]:
arr = np.array([1, 2, 3, 6, 4, 5])
rev=arr[::-1]
print(arr)
print(rev)

[1 2 3 6 4 5]
[5 4 6 3 2 1]


B. Flatten the NumPy arr:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods 

In [20]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

flattened_array1 = array1.flatten()
flattened_array2 = array1.ravel()

print(flattened_array1)
print(flattened_array2)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


C. Compare the following numpy arrays:

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [21]:
arr1 = np.array([[1, 2], [3, 4]])
#arr2 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 5], [3, 4]])

if np.array_equal(arr1, arr2):
    print("Arrays are Equal")
else:
    print("Arrays are not equal")

Arrays are not equal


D. Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 

In [22]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

most_frequent_x = np.bincount(x).argmax()
indices_x = np.where(x == most_frequent_x)

most_frequent_y = np.bincount(y).argmax()
indices_y = np.where(y == most_frequent_y)

print(f'Most Frequent in X: {most_frequent_x}, Indices: {indices_x}')
print(f'Most Frequent in Y: {most_frequent_y}, Indices: {indices_y}')

Most Frequent in X: 1, Indices: (array([0, 5, 7, 8, 9], dtype=int64),)
Most Frequent in Y: 1, Indices: (array([0, 1, 2], dtype=int64),)


E. For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find:

i. Sum of all elements

ii. Sum of all elements row-wise

iii. Sum of all elements column-wise

In [23]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum=gfg.sum()
row=gfg.sum(axis=0)
col=gfg.sum(axis=1)

print(f'Total Sum:{sum}, Rows Sum:{row},\nColumn Sum:\n{col}')

Total Sum:45, Rows Sum:[[20  9 16]],
Column Sum:
[[14]
 [16]
 [15]]


F. For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

i. Sum of diagonal elements

ii. Eigen values of matrix

iii. Eigen vectors of matrix

iv. Inverse of matrix

v. Determinant of matrix

In [24]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

sum_diagonal = np.trace(n_array)
eigen_values, eigen_vectors = np.linalg.eig(n_array)
inverse = np.linalg.inv(n_array)
determinant = np.linalg.det(n_array)

print(sum_diagonal)
print(eigen_values)
print(eigen_vectors)
print(inverse)
print(determinant)

176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


G. Multiply the following matrices and also find covariance between matrices using NumPy:

i. p = [[1, 2], [2, 3]]   q = [[4, 5], [6, 7]]

ii. p = [[1, 2], [2, 3], [4, 5]]  q = [[4, 5, 1], [6, 7, 2]]

In [25]:
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

multiplication1 = np.dot(p1, q1)
print(f'The multiplication of both matrices is:\n{multiplication1}')

p1_flat = p1.flatten()
q1_flat = q1.flatten()
covariance1 = np.cov(p1_flat, q1_flat)
print(f'The covariance of both matrices is:\n{covariance1}')

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

multiplication2 = np.dot(p2, q2)
print(f'The multiplication of both matrices is:\n{multiplication2}')

p2_flat = p2.flatten()
q2_flat = q2.flatten()
covariance2 = np.cov(p2_flat, q2_flat)
print(f'The covariance of both matrices is:\n{covariance2}')

The multiplication of both matrices is:
[[16 19]
 [26 31]]
The covariance of both matrices is:
[[0.66666667 1.        ]
 [1.         1.66666667]]
The multiplication of both matrices is:
[[16 19  5]
 [26 31  8]
 [46 55 14]]
The covariance of both matrices is:
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


H. For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),

find inner, outer and cartesian product?

In [26]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner_product = np.inner(x, y)
outer_product = np.outer(x, y)
cartesian=np.array(np.meshgrid(x, y)).T.reshape(-1, 2)
print(f'Inner Product: {inner_product}')
print(f'Outer Product: {outer_product}')
print(f'Cartesian Product: {cartesian}')

Inner Product: [[17 52]
 [13 62]]
Outer Product: [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian Product: [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


Q2. BASED ON NUMPY MATHEMATICS AND STATISTICS

A. For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

i. Find element-wise absolute value

ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row.

iii. Mean, Median and Standard Deviation of flattened array, of each column, and each row 

In [27]:
array = np.array([[1, -2, 3], [-4, 5, -6]])

abs_values = np.abs(array)

percentile_25 = np.percentile(array.flatten(), 25)
percentile_50 = np.percentile(array.flatten(), 50)
percentile_75 = np.percentile(array.flatten(), 75)

mean_val = np.mean(array)
median_val = np.median(array)
std_dev_val = np.std(array)

print(abs_values)
print(percentile_25, percentile_50, percentile_75)
print(mean_val, median_val, std_dev_val)

[[1 2 3]
 [4 5 6]]
-3.5 -0.5 2.5
-0.5 -0.5 3.8622100754188224


B. For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]).
Find floor, ceiling and truncated value, rounded values

In [28]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor = np.floor(a)
ceiling = np.ceil(a)
truncated = np.trunc(a)
rounded = np.round(a)

print(floor)
print(ceiling)
print(truncated)
print(rounded)

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


Q3. BASED ON SEARCHING AND SORTING

A. For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

i. Sorted array

ii. Indices of sorted array

iii. 4 smallest elements

iv. 5 largest elements

In [29]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array = np.sort(array)
sorted_indices = np.argsort(array)
smallest_4 = np.sort(array)[:4]
largest_5 = np.sort(array)[-5:]

print(sorted_array)
print(sorted_indices)
print(smallest_4)
print(largest_5)

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


B. For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find

i. Integer elements only

ii. Float elements only

In [30]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

integer_elements = array[array == array.astype(int)]
float_elements = array[array != array.astype(int)]

print(integer_elements)
print(float_elements)

[1. 2. 3. 2.]
[1.2 2.2]


Q4. 

A. Write a function named img_to_array(path) that reads an image from a specified path and save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale images)

In [31]:
import cv2

def img_to_array(path):
    img = cv2.imread(path)
    if len(img.shape) == 3:  # RGB image
        np.savetxt('image_rgb.txt', img.reshape(-1, img.shape[2]), fmt='%d')
    else:  # Grayscale image
        np.savetxt('image_greyscale.txt', img, fmt='%d')
img_to_array('C:/Users/DELL/.vscode/DataMining/Assignment1/plant.jpg')
